language: node_js
node_js:
  - "0.10"
services:
  - mongodb
deploy:
  provider: openshift
  user: $OPENSHIFT_USER
  password: $OPENSHIFT_PASSWORD
  domain: "dml"
  app:
    master: "vacacionespermanentes"
    dev: "vacacionespermanentesdev"
