language: node_js
node_js:
  - "0.12"
services:
  - mongodb
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app:
    master: "vacaciones-permanentes-master"
    dev: "vacaciones-permanentes-devel"
